### ISSUE TITLE
Missing "Mole_BERT" module

### ISSUE THREAD

**Issue by orli91** [kotori-y/mpek#4]
Dear authors,
I am trying to use your model but it appears it does not find the Mole_BERT module
before reading any input.
In datasetes/__init__.py fails to import the "Mole_BERT.loader", which is apparently missing from pre-requisite packages or data folder structure.
How can this be installed properly?
Marco

Traceback (most recent call last):
  File "evaluate.py", line 21, in <module>
    from MTLKcatKM.datasets import MTLKDataset
  File "/home/marco/Scrivania/mpek/MTLKcatKM/../MTLKcatKM/datasets/__init__.py", line 19, in <module>
    from Mole_BERT.loader import mol_to_graph_data_obj_simple
ModuleNotFoundError: No module named 'Mole_BERT'

**Comment by Decemberus** [comment]
> Dear authors, I am trying to use your model but it appears it does not find the Mole_BERT module before reading any input. In datasetes/**init**.py fails to import the "Mole_BERT.loader", which is apparently missing from pre-requisite packages or data folder structure. How can this be installed properly? Marco
> 
> Traceback (most recent call last): File "evaluate.py", line 21, in from MTLKcatKM.datasets import MTLKDataset File "/home/marco/Scrivania/mpek/MTLKcatKM/../MTLKcatKM/datasets/**init**.py", line 19, in from Mole_BERT.loader import mol_to_graph_data_obj_simple ModuleNotFoundError: No module named 'Mole_BERT'

Hello! I have encountered the same problem. I would like to ask if you have any ideas to solve this problem now?
